config/routes.rb
Rails.application.routes.draw do
  get 'users/confirm_expense'

  get 'expenses/notice_expense'

  #devise_for :customers
  #devise_for :admins
  get 'users/show'
  get 'homes/index'
  get 'expense/new'
  get 'expense/notice_expense'
  #root 'homes#index'
  
  devise_scope :user do
    root :to => "devise/sessions#new"
    end
    resource :users, only: [:show, :notice_expense,:confirm_expense]
    resource :expenses, only: [:new, :notice_expense,:confirm_expense]  
    #resources :user,only: [:show,:index,:edit,:update]
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  resources :expenses do
      collection {post :import}
      member do
      get 'expense_request'
      get 'notice_expense'
      get 'approval_expense'
      get 'confirm_expense'
      get 'expense_create'
      delete 'expense_destroy'
    end
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exoenses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]
  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :exception  
  before_action :set_expense, only: :show
  before_action :set_user, only: :show
  #before_action :expense_id, only: :show

  def show
    @expense = Expense.all
    @expenses_sum = @expense.all.sum(:expenses_money)
    @expenses_request = @expenses.find_by(update_expense_day: @first_day)
    @expenses_request_count = Expense.where(expense_confirmation: @user.name, expense_confirmation_status: "申請中").count
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_expense_form.html.erb
<%= form_with(model: @expense, url:expense_create_expense_path(id: current_user.id), method: :get,local: true) do |f| %>
  <div class="center-block" style="width: 500px;">
  
  <%= f.label :日付, class: "label-#{yield(:class_text)}" %>
  <%= f.date_field :expenses_day, in:1..100, class: "form-control" %>
  
  <%= f.label :経費備考, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :expenses_note, class: "form-control",style:"width: 500px" %>
  
  <%= f.label :経費金額, class: "label-#{yield(:class_text)} " %>
  <%= f.text_field :expenses_money, class: "form-control",style:"width: 500px" %><br>
  
  <%= f.submit :新規追加, class: "form-control btn btn-primary #{yield(:class_text)}" %>
  
  </div>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <% provide(:title, @user.name) %>
  <div>
    <table class="Lexpense">
      <thead class="Lexpense">
        <tr>
          <td class="h3">
          <table  class="Lexpense ">
          <tr>
          <td><%= link_to "◀", users_path(id: current_user.id, date: @first_day.prev_month) %>
            <%= l(@first_day, format: :middle) %> 経 費 精 算 表
          <%= link_to "▶", users_path(id: current_user.id, date: @first_day.next_month) %></td></tr>
          <tr><td>名前 <%= @user.name %></td></tr>
           </table>
           </td>
           <td class="h6">
           <table border="1px", class="Rexpense bg-info ">
           <tr>
          <th class="h7", style="width: 120px">清算確認</th>
          <td  class="h7", style="width: 200px">
           <% if @expenses_request.present?%>
            <% if @expenses_request.user_id == current_user.id %>
              <% unless @expenses_request == nil %>
                <% if @expenses_request.expense_confirmation_status == "申請中" %>
                 <%= @expenses_request.expense_confirmation %>へ申請中
                <% end %>
                <% if @expenses_request.expense_confirmation_status == "承認" %>
                  <%= @expenses_request.expense_confirmation %>承認済
                <% end %>
            <% end %>
            <% else %>
              <%="―—"%>
            <% end %>
          <% else %>
              <%="―—"%>
           <% end %>
          <% end %>
          </td>
          </tr>
          <tr>
          <th class="h7">承認金額</th>
          <td class="h7">
           <% if @expenses_request.present?%>
            <% if @expenses_request.user_id == current_user.id %>
              <% unless @expenses_request == nil %>
                <% if @expenses_request.expense_confirmation_status == "申請中" %>
                <%= number_to_currency(@expenses_request.request_money, unit: " ¥", strip_insignificant_zeros: true) %>
                <% end %>
                <% if @expenses_request.expense_confirmation_status == "承認" %>
                <%= number_to_currency(@expenses_request.request_money, unit: " ¥", strip_insignificant_zeros: true) %>
                <% end %>
              <% end %>
              <% else %>
                <%="　　¥0　　"%>
            <% end %>
           <% else %>
            <%="　　¥0　　"%>
           <% end %>
          </td>
        </tr>
      </thead>
    </table>
    </td>
    </tr>
    </table>
    </div>
      <% if @expenses_request_count > 0 %>
        <div>
          <nav border="px", class="expenserequest">
            <div>
              <%= link_to "経費清算申請があります。", notice_expense_expense_path(id: current_user.id), remote: true, class:"expenserequest"%>
            </div>
          </nav>
        </div>
      <% end %>
        <table border="3px", class="expensebody bg-info ">
          <tbody class="expensebody2">
            <tr>
              <th class="h8">日付</th>
              <th class="h8">　経　費　備　考　</th>
              <th class="h8", style="width: 130px">経　費　金　額</th>
              <th class="h8", style="width: 100px">　　　</th>
            </tr>
          </tbody>
          <tbody class="expensebody2">
            <% @expenses.each do |exp| %>
              <tr>
                <% if exp.user_id == current_user.id %>
                 <td><%= l(exp.expenses_day, format: :short)  %></td>
                 <td><%= exp.expenses_note %></td>
                 <td><%= number_to_currency(exp.expenses_money, unit: "¥ ", strip_insignificant_zeros: true) %></td>
                 <td><%= link_to "削除", expense_destroy_expense_path(exp.id),method: :delete,
                                  data: { confirm: "削除してもよろしいですか？" },
                                  class: "btn btn-primary btn-sm" %></td>
                <% end %>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
           <div>
          <tbody>
         <tr>
          <div class="panel panel-default expense_table">
            <div class="panel-heading">
              <button type="button" data-toggle="collapse" data-target="#collapse" class="btn btn-primary btn-xs">経 費 追 加</button>
            </div>
          </div>
            <div id="collapse" class="panel-collapse collapse">
              <div class="panel-body"><%= render 'expense_form' %></div>
          </tr>
                  </tbody>
       </div>
       <div>
               <table border="1px", class="expensebody bg-info ">

          <tfoot>
            <tr>
              <td>
                  <%= form_with(model: @expense, url: expense_request_expense_path(id: current_user.id),local: true,  method: :get) do |f| %>
                  <% %>承認者選択
                  <%= f.select :expense_confirmation, options_from_collection_for_select( User.all, :name, :name, 1), {include_blank: true}, {style:"width: 270px"} %>
                  <%= f.hidden_field :update_expense_day, :value => @first_day %>
                  <%= f.hidden_field :user_id, :value => @user.id %>
                  <%= f.hidden_field :request_money, :value => @expenses_sum %>
                  <%= f.hidden_field :expense_confirmation_status, :value => "承認" %>
                <td style="width: 130px"><%= number_to_currency(@expenses_sum, unit: "合計 ¥ ", strip_insignificant_zeros: true) %></td>
                <td style="width: 100px"><%= f.submit "清算承認", class: "btn-top btn-primary btn-xsm" %></td>
            </td>
            </tr>
          </tfoot>
       </table>
      </div>
  </div>
  <% end %>
  <div id="notice-expense" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>