config/routes.rb
Rails.application.routes.draw do
  get 'users/confirm_expense'

  get 'expenses/notice_expense'

  #devise_for :customers
  #devise_for :admins
  get 'users/show'
  get 'homes/index'
  get 'expense/new'
  get 'expense/notice_expense'
  #root 'homes#index'
  
  devise_scope :user do
    root :to => "devise/sessions#new"
    end
    resource :users, only: [:show, :notice_expense,:confirm_expense]
    resource :expenses, only: [:new, :notice_expense,:confirm_expense]  
    #resources :user,only: [:show,:index,:edit,:update]
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  resources :expenses do
      collection {post :import}
      member do
      get 'expense_request'
      get 'notice_expense'
      get 'approval_expense'
      get 'confirm_expense'
      get 'expense_create'
      delete 'expense_destroy'
    end
  end
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_expense, only: [:expense_request,:confirm_expense, :approval_expense, :notice_expense]
  before_action :set_user, only: :show
  
  def expense_id
    @expenses = Expense.find(params[:id])
  end

  def new
  end
   
  def expense_create
    @expense = Expense.all
    @expenses = Expense.new(expense_params)
    if @expenses.save
      flash[:success] = '経費が追加されました。'
      redirect_to users_path(id: current_user.id)
    else
      render '/users'
    end
  end
  
  def expense_destroy
    @expense = Expense.all
    @expenses = Expense.find(params[:id])
    @expenses.destroy
    flash[:success] = "#{@expenses.expenses_note}の経費を削除しました。"
    redirect_to users_path(id: current_user.id)
  end
  
  def expense_request
    ActiveRecord::Base.transaction do
      @user = User.find(params[:id])
      unless expense_params[:expense_confirmation].blank?
        @expenses.update(expense_params)
        flash[:success] = "経費清算を承認しました。"
      else
        flash[:success] = "申請先を選択してください。"
      end
      redirect_to users_path(id: current_user.id)
    end
  end
  
  def notice_expense
    @user = User.find(params[:id])
    @expenses_sum = @expenses.all.sum(:expenses_money)
    @expenses_notices =  Expense.where(expense_confirmation: @user.name, expense_confirmation_status: "申請中").group_by(&:user_id)
  end
  
  def confirm_expense
    @user = User.find(params[:id])
    @expense = Expense.all
    @expenses_sum = @expenses.all.sum(:expenses_money)
    @expenses_request = @expenses.find_by(update_expense_day: @first_day)
    @expenses_request_count = Expense.where(expense_confirmation: @user.name, expense_confirmation_status: "申請中").count
  end
  
  def approval_expense
    ActiveRecord::Base.transaction do
      @expenses_request = @expenses.find_by(update_expense_day: @first_day)
      @expenses_request_count = Expense.where(expense_confirmation: @user.name, expense_confirmation_status: "申請中")
      @expenses_notices =  Expense.where(expense_confirmation: @user.name, expense_confirmation_status: "申請中").group_by(&:user_id)
      @user = User.find(params[:id])
          if @expenses_notices[:expense_confirmation_status] = "承認"
            @expenses_notices.update(request_params)
          flash[:success] = "経費申請を承認しました"
        else
        flash[:danger] = "無効な入力データがあった為更新をキャンセルしました。"
        end
        redirect_to users_path(id: current_user.id)
      end
    end
  end
    
  def edit_overwork_request
    @user = User.find(params[:user_id])
    @attendance = @user.attendances.find(params[:id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end
  private
  
  def expense_params
    params.require(:expense).permit(:expenses_day, :expenses_note, :expenses_money, :expense_confirmation , :update_expense_day , :expense_confirmation_status , :request_money).merge(user_id: current_user.id)
  end
  
  def request_params
    params.permit(Expense:[:expenses_day, :expenses_note, :expenses_money, :expense_confirmation , :update_expense_day , :expense_confirmation_status , :request_money]).merge(user_id: @user.id)
  end

  

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_notice_expense.html.erb
<div class="modal-dialog modal-lg modal-dialog-center ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
        </button>
        <div>
            <% @expenses_notices.each do |id, expenses| %>
             <%= form_with(model: @expense, url: approval_expense_expense_path(User.find(id)), local: true, method: :get) do |f| %>
              <div class="h10"><%= User.find(id).name %>から経費清算申請</div>
                <table class="table table-bordered table-striped table-condensed" id="table-expenses">
                  <thead>
                    <th>年月</th>
                    <th>　　申請金額　　</th>
                    <th>　承認者確認　</th>
                    <th></th>
                  </thead>
                  <% @expenses.each do |att_notice| %>
                    <%= f.fields_for "expenses[]", att_notice do |d| %>
                      <tbody>
                        <tr>
                          <td><%= l(@first_day, format: :middle) %></td>
                          <td><%= number_to_currency(att_notice.expenses_money, unit: "¥ ", strip_insignificant_zeros: true) %></td>
                          <td><%= d.select :expense_confirmation_status, [["申請中"],["承認"]] , {}, {:class => "form-control"} %>
                           <%= d.hidden_field :expense_confirmation_status, :value => "承認" %>
                          <td><%= link_to "経費申請を確認", confirm_expense_expense_path(User.find(id)), class: "btn btn-primary btn-sm" %></td>
                        </tr>
                      </tbody>
                    <% end %>
                  <% end %>
                </table>
                <%= f.submit "承認内容を送信する", class: "btn btn-primary center-block h11" %>
              <% end %>
            <% end %>
          </div>
        </div> 
      </div>
    </div>
  </div>               

app/views/expenses/confirm_expense.html.erb
<% if user_signed_in? %>
  <% provide(:title, @user.name) %>
  <td>　　</td>
  <td>　</td>
  <div>
    <table class="Lexpense">
     <thead class="Lexpense">
        <tr>
         <td class="h3">
          <table  class="Lexpense">
          <tr>
          <td>
            <%= l(@first_day, format: :middle) %> 経 費 精 算 表
          </td></tr>
          <tr><td>名前 <%= @user.name %></td></tr>
           </table>
           </td>
           <td class="h6">
           <table border="", class="Rexpense">
           <tr>
          <th class="h7", style="width: 120px">清算確認</th>
          <td  class="h7", style="width: 200px">
           <% if @expenses_request.present?%>
              <% unless @expenses_request == nil %>
                <% if @expenses_request.expense_confirmation_status == "申請中" %>
                 <%= @expenses_request.expense_confirmation %>へ申請中
                <% end %>
                <% if @expenses_request.expense_confirmation_status == "承認" %>
                  <%= @expenses_request.expense_confirmation %>承認済
            <% end %>
            <% else %>
              <%="―—"%>
            <% end %>
          <% else %>
              <%="―—"%>
           <% end %>
          <% end %>
          </td>
          </tr>
          <tr>
          <th class="h7">申請金額</th>
          <td class="h7">
           <% if @expenses_request.present?%>
              <% unless @expenses_request == nil %>
                <% if @expenses_request.expense_confirmation_status == "申請中" %>
                <%= number_to_currency(@expenses_request.request_money, unit: " ¥", strip_insignificant_zeros: true) %>
                <% end %>
                <% if @expenses_request.expense_confirmation_status == "承認" %>
                <%= number_to_currency(@expenses_request.request_money, unit: " ¥", strip_insignificant_zeros: true) %>　　
              <% end %>
              <% else %>
                <%="　　¥0　　"%>
            <% end %>
           <% else %>
            <%="　　¥0　　"%>
           <% end %>
          </td>
        </tr>
      </thead>
    </table>
    </td>
    </tr>
    </table>
    </div>
       <table border="", class="expensebody">
          <tbody class="expensebody2">
            <tr>
              <th class="h8">日付</th>
              <th class="h8">　経　費　備　考　</th>
              <th class="h8", style="width: 160px">経　費　金　額</th>
            </tr>
          </tbody>
          <tbody class="expensebody2">
            <% @expenses.each do |exp| %>
              <tr>
                 <td><%= l(exp.expenses_day, format: :short)  %></td>
                 <td><%= exp.expenses_note %></td>
                 <td><%= number_to_currency(exp.expenses_money, unit: "¥ ", strip_insignificant_zeros: true) %></td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
  </div>

app/views/expenses/notice_expense.js.erb
$("#notice-expense").html("<%= escape_javascript(render 'notice_expense') %>");
$("#notice-expense").modal("show");